import type { ServiceCategory } from './walkabilityTypes'

// `saturation` (S) tunes how quickly a category satisfies. Essentials (you only need one or two
// nearby) saturate fast → small S. Amenity richness (more & more varied is genuinely better)
// saturates slowly → large S. See walkabilityScore.ts for the decay+saturation formula.
export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'supermarket',
    label: 'Supermarket',
    emoji: '🏪',
    topN: 3,
    saturation: 1.0,
    weight: 1,
    matches: (p) => p.shop === 'supermarket',
  },
  {
    id: 'pharmacy',
    label: 'Pharmacy',
    emoji: '💊',
    topN: 1,
    saturation: 0.8,
    weight: 1,
    matches: (p) => p.amenity === 'pharmacy',
  },
  {
    id: 'park',
    label: 'Park',
    emoji: '🌿',
    topN: 3,
    saturation: 1.2,
    weight: 1,
    matches: (p) => p.leisure === 'park',
  },
  {
    id: 'school',
    label: 'School',
    emoji: '🎓',
    topN: 2,
    saturation: 1.0,
    weight: 1,
    matches: (p) => p.amenity === 'school',
  },
  {
    id: 'kindergarten',
    label: 'Kindergarten',
    emoji: '🧸',
    topN: 2,
    saturation: 1.0,
    weight: 1,
    matches: (p) => p.amenity === 'kindergarten',
  },
  {
    id: 'clinic',
    label: 'Clinic',
    emoji: '🏥',
    topN: 1,
    saturation: 0.8,
    weight: 1,
    matches: (p) => p.amenity === 'doctors' || p.amenity === 'clinic',
  },
  {
    id: 'metro',
    label: 'Metro',
    emoji: '🚇',
    topN: 1,
    saturation: 0.7,
    weight: 1,
    // Use station=subway only — subway_entrance gives one node per physical door (3-5 per station)
    matches: (p) => p.station === 'subway',
  },
  {
    id: 'cafe',
    label: 'Cafe',
    emoji: '☕',
    topN: 1,
    saturation: 3.0,
    weight: 1,
    matches: (p) => p.amenity === 'cafe',
  },
  {
    id: 'restaurant',
    label: 'Restaurant',
    emoji: '🍽️',
    topN: 3,
    saturation: 3.0,
    weight: 1,
    matches: (p) => p.amenity === 'restaurant',
  },
  {
    id: 'beach',
    label: 'Beach',
    emoji: '🏖️',
    topN: 1,
    saturation: 0.6,
    weight: 1,
    matches: (p) => p.natural === 'beach',
  },
]
